Fix `goenv/go-build`
* Fix few mentions of pyenv. Guess replacing `pyenv => goenv` didn't quite work
* Improve readability
* Add debug support for `goenv-uninstall`
* Fix goenv-uninstall error messages starting with backtick character
and ending with single quote character. Now all start and end with
single quotes.
* Fix difference in behavior of `goenv-uninstall` when `-f` or `--force`
is given and when it's not.
Now it always checks if the version exists and fails with exit status 1 if it's missing.
Note that now `{before,after}_uninstall` hooks get triggered only if
version to be uninstalled exists.

diff --git a/plugins/go-build/bin/go-build b/plugins/go-build/bin/go-build
--- a/plugins/go-build/bin/go-build
+++ b/plugins/go-build/bin/go-build
@@ -21,9 +21,7 @@ set -E
 exec 3<&2 # preserve original stderr at fd 3
 
 # Verbose output in debug mode
-[ -n "$GOENV_DEBUG" ] && {
-    set -x
-}
+[ -n "$GOENV_DEBUG" ] && set -x
 
 lib() {
   parse_options() {
@@ -85,8 +83,10 @@ sanitize() {
 }
 
 colorize() {
-  if [ -t 1 ]; then printf "\e[%sm%s\e[m" "$1" "$2"
-  else echo -n "$2"
+  if [ -t 1 ]; then
+    printf "\e[%sm%s\e[m" "$1" "$2"
+  else
+    echo -n "$2"
   fi
 }
 
@@ -125,7 +125,8 @@ osx_version() {
 }
 
 build_failed() {
-  { echo
+  {
+    echo
     colorize 1 "BUILD FAILED"
     echo " ($(os_information) using $(version))"
     echo
@@ -302,7 +303,8 @@ install_package_using() {
   make_package "$package_name"
   popd >&4
 
-  { echo "Installed ${package_name} to ${PREFIX_PATH}"
+  {
+    echo "Installed ${package_name} to ${PREFIX_PATH}"
     echo
   } >&2
 }
@@ -390,7 +392,8 @@ verify_checksum() {
   40) checksum_command="compute_sha1" ;;
   64) checksum_command="compute_sha2" ;;
   *)
-    { echo
+    {
+      echo
       echo "unexpected checksum length: ${#expected_checksum} (${expected_checksum})"
       echo "expected 0 (no checksum), 32 (MD5), 40 (SHA1) or 64 (SHA2-256)"
       echo
@@ -406,7 +409,8 @@ verify_checksum() {
   [ -n "$computed_checksum" ] || return 1
 
   if [ "$expected_checksum" != "$computed_checksum" ]; then
-    { echo
+    {
+      echo
       echo "checksum mismatch: ${filename} (file is corrupt)"
       echo "expected $expected_checksum, got $computed_checksum"
       echo
@@ -426,7 +430,7 @@ http() {
   elif type wget &>/dev/null; then
     "http_${method}_wget" "$url" "$file"
   else
-    echo "error: please install \`curl\` or \`wget\` and try again" >&2
+    echo "error: please install 'curl' or 'wget' and try again" >&2
     exit 1
   fi
 }
@@ -503,7 +507,8 @@ fetch_tarball() {
     download_tarball "$package_url" "$package_filename" "$checksum"
   fi
 
-  { if tar $tar_args "$package_filename"; then
+  {
+    if tar $tar_args "$package_filename"; then
       if [ -z "$KEEP_BUILD_PATH" ]; then
         rm -f "$package_filename"
       else
@@ -549,7 +554,8 @@ download_tarball() {
 
   if [ -n "$GO_BUILD_CACHE_PATH" ]; then
     local cached_package_filename="${GO_BUILD_CACHE_PATH}/$package_filename"
-    { mv "$package_filename" "$cached_package_filename"
+    {
+      mv "$package_filename" "$cached_package_filename"
       ln -s "$cached_package_filename" "$package_filename"
     } >&4 2>&1 || return 1
   fi
@@ -567,7 +573,8 @@ fetch_git() {
       pushd "$GO_BUILD_CACHE_PATH" >&4
       local clone_name="$(sanitize "$git_url")"
       if [ -e "${clone_name}" ]; then
-        { cd "${clone_name}"
+        {
+          cd "${clone_name}"
           git fetch --force "$git_url" "+${git_ref}:${git_ref}"
         } >&4 2>&1
       else
@@ -615,7 +622,8 @@ fetch_zip() {
     download_tarball "$package_url" "$package_filename" "$checksum"
   fi
 
-  { if unzip "$package_filename"; then
+  {
+    if unzip "$package_filename"; then
       if [ -z "$KEEP_BUILD_PATH" ]; then
         rm -f "$package_filename"
       else
@@ -722,12 +730,13 @@ verify_go() {
   fi
 
   if [ ! -x "${GO_BIN}" ]; then
-    { colorize 1 "ERROR"
+    {
+      colorize 1 "ERROR"
       echo ": invalid Go executable: ${GO_BIN}"
       echo
       echo "The go-build could not find proper executable of Go after successful build."
       echo "Please open an issue for future improvements."
-      echo "https://github.com/yyuu/goenv/issues"
+      echo "https://github.com/syndbg/goenv/issues"
       return 1
     } >&3
   fi
@@ -735,7 +744,8 @@ verify_go() {
 
 try_go_module() {
   if ! "$GO_BIN" -c "import $1" 1>/dev/null 2>&1; then
-    { colorize 1 "WARNING"
+    {
+      colorize 1 "WARNING"
       echo ": The Go $1 extension was not compiled. Missing the ${2:-$1}?"
       return 0
     } >&3
@@ -744,11 +754,12 @@ try_go_module() {
 
 verify_go_module() {
   if ! "$GO_BIN" -c "import $1" 1>/dev/null 2>&1; then
-    { colorize 1 "ERROR"
+    {
+      colorize 1 "ERROR"
       echo ": The Go $1 extension was not compiled. Missing the ${2:-$1}?"
       echo
       echo "Please consult to the Wiki page to fix the problem."
-      echo "https://github.com/yyuu/goenv/wiki/Common-build-problems"
+      echo "https://github.com/syndbg/goenv/wiki/Common-build-problems"
       echo
       return 1
     } >&3
@@ -771,7 +782,8 @@ usage() {
 }
 
 list_definitions() {
-  { for DEFINITION_DIR in "${GO_BUILD_DEFINITIONS[@]}"; do
+  {
+    for DEFINITION_DIR in "${GO_BUILD_DEFINITIONS[@]}"; do
       [ -d "$DEFINITION_DIR" ] && find "$DEFINITION_DIR" -maxdepth 1 -type f -print0 | xargs -0 -n 1 basename 2>/dev/null
     done
   } | sort_versions | uniq
