feat: Allow major or minor version lookup

diff --git a/libexec/goenv-version-file-write b/libexec/goenv-version-file-write
--- a/libexec/goenv-version-file-write
+++ b/libexec/goenv-version-file-write
@@ -1,6 +1,8 @@
 #!/usr/bin/env bash
 # Summary: Writes specified version(s) to the specified file if the version(s) exist
 # Usage: goenv version-file-write <file> <version>
+# If the specified version is not installed, only display error message and return error code.
+# If only a single version="system" is specified and installed, display previous version (if any) and remove file.
 
 set -e
 [ -n "$GOENV_DEBUG" ] && set -x
@@ -14,12 +16,46 @@ if [ -z "$versions" ] || [ -z "$GOENV_VERSION_FILE" ]; then
   exit 1
 fi
 
-# Make sure the specified version is installed.
-goenv-prefix "${versions[@]}" >/dev/null
+# Make sure the specified version(s) are installed.
+# Use goenv-prefix loop logic.
+if [ -n "$1" ]; then
+  OLDIFS="$IFS"
+  {
+    IFS=:
+    export GOENV_VERSION="$*"
+  }
+  IFS="$OLDIFS"
+elif [ -z "$GOENV_VERSION" ]; then
+  GOENV_VERSION="$(goenv-version-name)"
+fi
 
-# Write the version out to disk.
-# Create an empty file. Using "rm" might cause a permission error.
-> "$GOENV_VERSION_FILE"
-for version in "${versions[@]}"; do
-  echo "$version" >> "$GOENV_VERSION_FILE"
-done
+GOENV_VERSIONS=()
+OLDIFS="$IFS"
+{
+  IFS=:
+  for version in ${GOENV_VERSION}; do
+    if ! INSTALLED="$(goenv-installed "$version" 2>&1)"; then
+      echo "$INSTALLED" >&2
+      exit 1
+    fi
+    GOENV_VERSIONS=("${GOENV_VERSIONS[@]}" "$INSTALLED")
+  done
+}
+IFS="$OLDIFS"
+
+# Special case: only system was specified and found
+if [ "$1" = "system" ]; then
+  if [ -f "$GOENV_VERSION_FILE" ]; then
+    if previous="$(head -1 "$GOENV_VERSION_FILE" | grep -E "^[0-9]+\.[0-9]+\.[0-9]+$")"; then
+      echo "goenv: using system version instead of $previous now"
+    fi
+    rm "$GOENV_VERSION_FILE"
+  fi
+else
+  # Write the version out to disk.
+  # Create an empty file. Using "rm" might cause a permission error.
+  > "$GOENV_VERSION_FILE"
+  for version in "${GOENV_VERSIONS[@]}"; do
+    echo "$version" >> "$GOENV_VERSION_FILE"
+  done
+fi
